name: 'web_analytics'
version: '1.0.0'
config-version: 2

profile: 'web_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
  - "target"
  - "dbt_packages"


models:
  web_analytics:
    +schema: web_analytics

seeds:
  web_analytics:
    +schema: web_analytics

on-run-end:
  - "{{ grant_select_on_schemas(schemas, 'reporter') }}"